-- Sistema de recomendación vocacional
-- PostgreSQL 13 o posterior.
-- Ejecutar dentro de la base de datos destinada al proyecto.
-- Los bloques 1 y 2 pueden ejecutarse por separado.

-- ============================================================
-- BLOQUE 1: CATÁLOGOS, USUARIOS, RELACIONES Y RESULTADOS
-- ============================================================

BEGIN;

CREATE TABLE public.area (
    id_area INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_area VARCHAR(150) NOT NULL
);

CREATE TABLE public.escuela (
    id_escuela INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_escuela VARCHAR(200) NOT NULL
);

CREATE TABLE public.habilidad (
    id_habilidad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion TEXT NOT NULL
);

CREATE TABLE public.carrera (
    id_carrera INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_carrera VARCHAR(200) NOT NULL,
    id_area INTEGER NOT NULL,
    CONSTRAINT fk_carrera_area
        FOREIGN KEY (id_area) REFERENCES public.area (id_area)
);

CREATE TABLE public.usuario (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid_usuario UUID NOT NULL DEFAULT gen_random_uuid(),
    nombre VARCHAR(60) NOT NULL,
    correo VARCHAR(150) NOT NULL,
    id_area INTEGER,
    CONSTRAINT uq_usuario_uuid UNIQUE (uuid_usuario),
    CONSTRAINT fk_usuario_area
        FOREIGN KEY (id_area) REFERENCES public.area (id_area)
);

CREATE TABLE public.carrera_escuela (
    id_carrera INTEGER NOT NULL,
    id_escuela INTEGER NOT NULL,
    CONSTRAINT pk_carrera_escuela PRIMARY KEY (id_carrera, id_escuela),
    CONSTRAINT fk_carrera_escuela_carrera
        FOREIGN KEY (id_carrera) REFERENCES public.carrera (id_carrera),
    CONSTRAINT fk_carrera_escuela_escuela
        FOREIGN KEY (id_escuela) REFERENCES public.escuela (id_escuela)
);

CREATE TABLE public.carrera_habilidad (
    id_carrera INTEGER NOT NULL,
    id_habilidad INTEGER NOT NULL,
    CONSTRAINT pk_carrera_habilidad PRIMARY KEY (id_carrera, id_habilidad),
    CONSTRAINT fk_carrera_habilidad_carrera
        FOREIGN KEY (id_carrera) REFERENCES public.carrera (id_carrera),
    CONSTRAINT fk_carrera_habilidad_habilidad
        FOREIGN KEY (id_habilidad) REFERENCES public.habilidad (id_habilidad)
);

-- Esta tabla NO tiene PK ni UNIQUE: las repeticiones son intencionales.
CREATE TABLE public.usuario_habilidad (
    uuid_usuario UUID NOT NULL,
    id_habilidad INTEGER NOT NULL,
    CONSTRAINT fk_usuario_habilidad_usuario
        FOREIGN KEY (uuid_usuario) REFERENCES public.usuario (uuid_usuario),
    CONSTRAINT fk_usuario_habilidad_habilidad
        FOREIGN KEY (id_habilidad) REFERENCES public.habilidad (id_habilidad)
);

CREATE TABLE public.resultado (
    id_resultado INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid_usuario UUID NOT NULL,
    id_carrera INTEGER NOT NULL,
    porcentaje_coincidencia NUMERIC(5,2) NOT NULL,
    top SMALLINT NOT NULL,
    CONSTRAINT uq_resultado_usuario_carrera UNIQUE (uuid_usuario, id_carrera),
    CONSTRAINT uq_resultado_usuario_top UNIQUE (uuid_usuario, top),
    CONSTRAINT fk_resultado_usuario
        FOREIGN KEY (uuid_usuario) REFERENCES public.usuario (uuid_usuario),
    CONSTRAINT fk_resultado_carrera
        FOREIGN KEY (id_carrera) REFERENCES public.carrera (id_carrera)
);


COMMIT;

-- ============================================================
-- BLOQUE 2: FORMULARIO STAR Y SU RELACIÓN CON ÁREA
-- Se deja al final para modificar o ejecutar este bloque aparte.
-- ============================================================

BEGIN;

CREATE TABLE public.formulario (
    id_formulario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_area INTEGER NOT NULL,
    pregunta_s TEXT NOT NULL,
    pregunta_t TEXT NOT NULL,
    pregunta_a TEXT NOT NULL,
    pregunta_r TEXT NOT NULL
);

COMMENT ON TABLE public.formulario IS
    'Formularios STAR definidos por área. Almacena las preguntas de Situación, Tarea, Acción y Resultado.';

ALTER TABLE public.formulario
    ADD CONSTRAINT fk_formulario_area
    FOREIGN KEY (id_area) REFERENCES public.area (id_area);

COMMIT;