-- Sistema de recomendación vocacional (Athena)
-- PostgreSQL 13 o posterior.
-- Ejecutar dentro de la base de datos destinada al proyecto.
-- Modelo: carrera 1:1 programa_academico (un objetivo por programa);
-- los perfiles de ingreso/egreso se modelan con el discriminador tipo_perfil
-- en la tabla puente carrera_criterio contra el catálogo maestro criterio.

-- ============================================================
-- BLOQUE 1: ENUM, CATÁLOGOS, USUARIOS, PROGRAMAS Y CRITERIOS
-- ============================================================

BEGIN;

-- Tipo de perfil para discriminar criterios de ingreso/egreso.
CREATE TYPE tipo_perfil_enum AS ENUM ('INGRESO', 'EGRESO');

CREATE TABLE public.area (
    id_area INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_area VARCHAR(150) NOT NULL
);

CREATE TABLE public.escuela (
    id_escuela INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_escuela VARCHAR(200) NOT NULL
);

CREATE TABLE public.carrera (
    id_carrera INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_carrera VARCHAR(200) NOT NULL,
    id_area INTEGER NOT NULL,
    CONSTRAINT fk_carrera_area
        FOREIGN KEY (id_area) REFERENCES public.area (id_area)
);

CREATE TABLE public.usuario (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid_usuario UUID NOT NULL DEFAULT gen_random_uuid(),
    nombre VARCHAR(60) NOT NULL,
    correo VARCHAR(150) NOT NULL,
    id_area INTEGER,
    CONSTRAINT uq_usuario_uuid UNIQUE (uuid_usuario),
    CONSTRAINT fk_usuario_area
        FOREIGN KEY (id_area) REFERENCES public.area (id_area)
);

CREATE TABLE public.carrera_escuela (
    id_carrera INTEGER NOT NULL,
    id_escuela INTEGER NOT NULL,
    CONSTRAINT pk_carrera_escuela PRIMARY KEY (id_carrera, id_escuela),
    CONSTRAINT fk_carrera_escuela_carrera
        FOREIGN KEY (id_carrera) REFERENCES public.carrera (id_carrera),
    CONSTRAINT fk_carrera_escuela_escuela
        FOREIGN KEY (id_escuela) REFERENCES public.escuela (id_escuela)
);

-- Programa académico: relación 1:1 con carrera (id_carrera UNIQUE),
-- con un único objetivo (texto fijo por programa/carrera).
CREATE TABLE public.programa_academico (
    id_programa INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_carrera INTEGER NOT NULL UNIQUE,
    objetivo TEXT NOT NULL,
    CONSTRAINT fk_programa_carrera
        FOREIGN KEY (id_carrera) REFERENCES public.carrera (id_carrera)
);

-- Catálogo maestro de criterios.
-- El perfil (ingreso/egreso) se discrimina en carrera_criterio.tipo_perfil.
CREATE TABLE public.criterio (
    id_criterio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion_criterio TEXT NOT NULL
);

-- Relación M:N carrera-criterio con discriminador de perfil (ingreso/egreso).
CREATE TABLE public.carrera_criterio (
    id_carrera INTEGER NOT NULL,
    id_criterio INTEGER NOT NULL,
    tipo_perfil tipo_perfil_enum NOT NULL,
    CONSTRAINT pk_carrera_criterio PRIMARY KEY (id_carrera, id_criterio, tipo_perfil),
    CONSTRAINT fk_carrera_criterio_carrera
        FOREIGN KEY (id_carrera) REFERENCES public.carrera (id_carrera),
    CONSTRAINT fk_carrera_criterio_criterio
        FOREIGN KEY (id_criterio) REFERENCES public.criterio (id_criterio)
);

-- Resultados de criterios del usuario (permite varios intentos vía repeticion).
CREATE TABLE public.usuario_criterio (
    uuid_usuario UUID NOT NULL,
    id_criterio INTEGER NOT NULL,
    cumplimiento FLOAT NOT NULL,
    repeticion INTEGER NOT NULL,
    CONSTRAINT pk_usuario_criterio PRIMARY KEY (uuid_usuario, id_criterio, repeticion),
    CONSTRAINT fk_usuario_criterio_usuario
        FOREIGN KEY (uuid_usuario) REFERENCES public.usuario (uuid_usuario),
    CONSTRAINT fk_usuario_criterio_criterio
        FOREIGN KEY (id_criterio) REFERENCES public.criterio (id_criterio)
);

-- Objetivos (de programa) seleccionados por el usuario.
CREATE TABLE public.usuario_objetivo (
    uuid_usuario UUID NOT NULL,
    id_programa INTEGER NOT NULL,
    porc_acertividad FLOAT NOT NULL,
    CONSTRAINT pk_usuario_objetivo PRIMARY KEY (uuid_usuario, id_programa),
    CONSTRAINT fk_usuario_objetivo_usuario
        FOREIGN KEY (uuid_usuario) REFERENCES public.usuario (uuid_usuario),
    CONSTRAINT fk_usuario_objetivo_programa
        FOREIGN KEY (id_programa) REFERENCES public.programa_academico (id_programa)
);

CREATE TABLE public.resultado (
    id_resultado INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid_usuario UUID NOT NULL,
    id_carrera INTEGER NOT NULL,
    porcentaje_coincidencia NUMERIC(5,2) NOT NULL,
    top SMALLINT NOT NULL,
    CONSTRAINT uq_resultado_usuario_carrera UNIQUE (uuid_usuario, id_carrera),
    CONSTRAINT uq_resultado_usuario_top UNIQUE (uuid_usuario, top),
    CONSTRAINT fk_resultado_usuario
        FOREIGN KEY (uuid_usuario) REFERENCES public.usuario (uuid_usuario),
    CONSTRAINT fk_resultado_carrera
        FOREIGN KEY (id_carrera) REFERENCES public.carrera (id_carrera)
);

COMMIT;

-- ============================================================
-- BLOQUE 2: FORMULARIO STAR Y SU RELACIÓN CON ÁREA
-- Se deja al final para modificar o ejecutar este bloque aparte.
-- ============================================================

BEGIN;

CREATE TABLE public.formulario (
    id_formulario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_area INTEGER NOT NULL,
    pregunta_s TEXT NOT NULL,
    pregunta_t TEXT NOT NULL,
    pregunta_a TEXT NOT NULL,
    pregunta_r TEXT NOT NULL
);

ALTER TABLE public.formulario
    ADD CONSTRAINT fk_formulario_area
    FOREIGN KEY (id_area) REFERENCES public.area (id_area);

COMMIT;
