name: Athena CI/CD

on:
  push:
    branches:
      - main

jobs:
  ValidateConection:
    runs-on: [self-hosted, k3s-devel]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validar Autenticación y Artifact Registry
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          # Crear archivo temporal para servicio
          echo '${{ secrets.GCP_SA_KEY }}' > "${HOME}/key.json"
          
          # Autenticar en Google Cloud y Docker
          gcloud auth activate-service-account --key-file="${HOME}/key.json"
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
          echo "✅ Autenticación en Google Cloud exitosa."
          
          # Confirmar acceso a Artifact Registry listando los repositorios
          echo "Listando repositorios en us-central1 para verificar permisos:"
          gcloud artifacts repositories list --location=us-central1 --project=$PROJECT_ID
          
          # Limpiar la llave por seguridad
          rm "${HOME}/key.json"
